//
//  GameViewController.swift
//  Asteroids
//
//  Created by David Long on 7/7/19.
//  Copyright © 2019 David Long. All rights reserved.
//

import UIKit
import SpriteKit

/// Main view controller, generated by Xcode
class GameViewController: UIViewController {
  override func viewDidLoad() {
    super.viewDidLoad()
    if let lang = Locale.preferredLanguages.first {
      /// - Todo: Ideally the game would be localized, at least for Spanish
      logging("Preferred language \(lang)")
    }
    if let view = self.view as! SKView? {
      let aspect = view.frame.width / view.frame.height
      // Save the scaling for use with control motions.  I want to specify motions in
      // terms of pts, since those correspond approximately to physical distances
      // that the players's fingers should move.
      Globals.ptsToGameUnits = 768 / view.frame.height
      logging("\(Globals.ptsToGameUnits) game units per pt")
      // Make physics bodies for irregular shapes
      Globals.conformingPhysicsCache.preload()
      // Build custom shaders for special effects
      precompileShaders()
      let size = CGSize(width: 768 * aspect, height: 768)
      // Create the main menu then trigger the Game Center authentication
      Globals.menuScene = MenuScene(size: size)
      Globals.gcInterface = GameCenterInterface(leaderboardID: "org.davidlong.Asteroids.normalScores",
                                                presenter: { vc in Globals.menuScene.setGameCenterAuth(viewController: vc) })
      // Show the intro on first launch, otherwise the main menu
      let toPresent = UserData.hasDoneIntro.value ? Globals.menuScene! : IntroScene(size: size, conclusion: false)
      logging("viewDidLoad will present \(toPresent.name!)")
      view.presentScene(toPresent)
      // Drawing preferences
      view.preferredFramesPerSecond = 120
      view.ignoresSiblingOrder = true
      // Debugging stuff
      view.showsFPS = true
      view.showsNodeCount = true
      view.showsDrawCount = true
      // view.showsPhysics = true
    }
  }

  override func viewWillLayoutSubviews() {
    super.viewWillLayoutSubviews()
    // The safe area is valid at this point; save the insets (converted to game
    // units) since I don't want to have actual game play going on in those areas.
    logging("viewWillLayoutSubviews saving safe area")
    Globals.safeAreaPaddingLeft = view.safeAreaInsets.left * Globals.ptsToGameUnits
    Globals.safeAreaPaddingRight = view.safeAreaInsets.right * Globals.ptsToGameUnits
  }

  override var shouldAutorotate: Bool {
    return true
  }

  override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
    // The game only makes sense in landscape mode
    return .landscape
  }

  override var prefersStatusBarHidden: Bool {
    // Hide the status bar
    return true
  }

  override var preferredScreenEdgesDeferringSystemGestures: UIRectEdge {
    // The app gets precedence for stuff happening at the bottom of the screen.  This
    // makes the home bar on devices without a home button fade to partial
    // transparency.
    return UIRectEdge.bottom
  }
}

extension Globals {
  /// The Game Center interface singleton
  static var gcInterface: GameCenterInterface!
  /// Multiply by this to convert from points to game units
  static var ptsToGameUnits = CGFloat(1)
  /// The game's main menu scene
  static var menuScene: MenuScene!
  /// Size of the device's left safe area in game units
  static var safeAreaPaddingLeft = CGFloat(0)
  /// Size of the device's right safe area in game units
  static var safeAreaPaddingRight = CGFloat(0)
}
